import mne
import numpy as np
import pytest
from numpy.testing import assert_allclose, assert_array_equal

from mne_connectivity import Connectivity, EpochConnectivity, read_connectivity
from mne_connectivity.graph_learning import learn_graph


def _make_synthetic_graph_signals(n_nodes, n_times, rng, structure="two_community"):
    """Build a known graph and Tikhonov-filtered smooth signals on it.

    Follows Kalofolias (2016) Sec. 6.1: signals are generated by filtering
    white noise with a Tikhonov (low-pass) graph filter, h(lambda) = 1 / (1 +
    10 * lambda), applied via the Laplacian eigendecomposition.
    """
    if structure == "ring":
        W = np.zeros((n_nodes, n_nodes))
        for i in range(n_nodes):
            W[i, (i + 1) % n_nodes] = 1.0
        W = np.maximum(W, W.T)
    elif structure == "two_community":
        half = n_nodes // 2
        W = np.zeros((n_nodes, n_nodes))
        W[:half, :half] = 1.0
        W[half:, half:] = 1.0
        np.fill_diagonal(W, 0)
        W[0, half] = W[half, 0] = 0.3  # sparse inter-community edge
    else:
        raise ValueError(structure)

    degrees = W.sum(axis=1)
    L = np.diag(degrees) - W
    eigvals, eigvecs = np.linalg.eigh(L)
    h = 1.0 / (1.0 + 10 * eigvals)
    noise = rng.standard_normal((n_nodes, n_times))
    X = eigvecs @ (h[:, np.newaxis] * (eigvecs.T @ noise))
    return X, W


def test_learn_graph_recovers_ground_truth():
    """Test that learn_graph recovers a known graph from smooth signals."""
    rng = np.random.default_rng(0)
    n_nodes = 10
    X, W_true = _make_synthetic_graph_signals(n_nodes, 2000, rng)

    conn = learn_graph(X, verbose=False)  # default alpha=0.5, beta=0.5
    assert isinstance(conn, Connectivity)

    dense = conn.get_data(output="dense")
    assert_array_equal(np.diag(dense), np.zeros(n_nodes))
    assert_allclose(dense, dense.T)  # symmetric

    triu = np.triu_indices(n_nodes, k=1)
    corr = np.corrcoef(W_true[triu], dense[triu])[0, 1]
    assert corr > 0.8


def test_learn_graph_beta_monotonicity():
    """Test that increasing beta yields non-decreasing graph density.

    beta=0 (the sparsest, but slowest-converging, setting) needs many more
    iterations than the default, so max_iter is bumped for this test only.
    """
    rng = np.random.default_rng(1)
    n_nodes = 8
    X, _ = _make_synthetic_graph_signals(n_nodes, 1000, rng)

    betas = [0.0, 0.1, 1.0, 10.0]
    n_nonzeros = []
    for beta in betas:
        conn = learn_graph(X, alpha=1.0, beta=beta, max_iter=10000, verbose=False)
        w = conn.get_data(output="dense")[np.triu_indices(n_nodes, k=1)]
        n_nonzero = np.count_nonzero(w > 1e-8)
        if beta == 0.0:
            assert n_nonzero >= n_nodes - 1  # at least a spanning-tree's worth
        n_nonzeros.append(n_nonzero)

    assert np.all(np.diff(n_nonzeros) >= 0)


def test_learn_graph_few_time_samples():
    """Test robustness of learn_graph with very few time samples."""
    rng = np.random.default_rng(2)
    n_nodes = 5
    X, W_true = _make_synthetic_graph_signals(n_nodes, 2000, rng)

    conn = learn_graph(X[:, :5], verbose=False)  # default alpha=0.5, beta=0.5
    dense = conn.get_data(output="dense")
    assert np.isfinite(dense).all()

    triu = np.triu_indices(n_nodes, k=1)
    corr = np.corrcoef(W_true[triu], dense[triu])[0, 1]
    assert corr > 0.0  # weaker threshold than the full-length case


def test_learn_graph_epochs_input():
    """Test learn_graph with an mne.Epochs input."""
    rng = np.random.default_rng(3)
    n_nodes, n_epochs, n_times_per_epoch = 6, 4, 300
    X, _ = _make_synthetic_graph_signals(n_nodes, n_epochs * n_times_per_epoch, rng)
    X3 = np.stack(
        [
            X[:, i * n_times_per_epoch : (i + 1) * n_times_per_epoch]
            for i in range(n_epochs)
        ]
    )
    info = mne.create_info(
        [f"ch{i}" for i in range(n_nodes)], sfreq=100.0, ch_types="eeg"
    )
    epochs = mne.EpochsArray(X3, info, verbose=False)

    conn = learn_graph(epochs, verbose=False)
    assert isinstance(conn, EpochConnectivity)
    assert conn.names == epochs.ch_names
    assert conn.n_nodes == n_nodes
    assert conn.get_data(output="raveled").shape == (
        n_epochs,
        (n_nodes + 1) * n_nodes // 2,
    )
    assert conn.get_data(output="dense").shape == (n_epochs, n_nodes, n_nodes)


def test_learn_graph_bare_2d_returns_connectivity():
    """Test that a bare 2D array returns Connectivity, not EpochConnectivity."""
    rng = np.random.default_rng(4)
    X, _ = _make_synthetic_graph_signals(5, 500, rng)
    conn = learn_graph(X, verbose=False)
    assert isinstance(conn, Connectivity)
    assert not isinstance(conn, EpochConnectivity)


def test_learn_graph_n_jobs_identical():
    """Test that n_jobs=1 and n_jobs=2 give identical results."""
    rng = np.random.default_rng(5)
    n_nodes, n_epochs, n_times_per_epoch = 5, 4, 200
    X, _ = _make_synthetic_graph_signals(n_nodes, n_epochs * n_times_per_epoch, rng)
    X3 = np.stack(
        [
            X[:, i * n_times_per_epoch : (i + 1) * n_times_per_epoch]
            for i in range(n_epochs)
        ]
    )

    conn_serial = learn_graph(X3, n_jobs=1, verbose=False)
    conn_parallel = learn_graph(X3, n_jobs=2, verbose=False)
    assert_allclose(conn_serial.get_data(), conn_parallel.get_data())


def test_learn_graph_roundtrip(tmp_path):
    """Test save/load round-trip of a learn_graph result."""
    rng = np.random.default_rng(6)
    n_nodes, n_epochs, n_times_per_epoch = 5, 3, 200
    X, _ = _make_synthetic_graph_signals(n_nodes, n_epochs * n_times_per_epoch, rng)
    X3 = np.stack(
        [
            X[:, i * n_times_per_epoch : (i + 1) * n_times_per_epoch]
            for i in range(n_epochs)
        ]
    )

    conn = learn_graph(X3, verbose=False)
    fname = tmp_path / "test-graph-connectivity.nc"
    conn.save(fname)
    read_conn = read_connectivity(fname)
    assert_array_equal(conn.get_data(), read_conn.get_data())


def test_learn_graph_duplicate_rows():
    """Test that duplicate (identical) channels don't break the solver."""
    rng = np.random.default_rng(7)
    n_nodes = 6
    X, _ = _make_synthetic_graph_signals(n_nodes, 1000, rng)
    X_dup = X.copy()
    X_dup[1] = X_dup[0]  # channel 1 is an exact duplicate of channel 0

    conn = learn_graph(X_dup, alpha=1.0, beta=0.0, max_iter=10000, verbose=False)
    dense = conn.get_data(output="dense")
    assert np.isfinite(dense).all()
    # the duplicate pair (zero distance) should get one of the largest weights
    triu = np.triu_indices(n_nodes, k=1)
    assert dense[0, 1] == dense[triu].max()


def test_learn_graph_convergence_warning():
    """Test that a warning is raised when max_iter is too small to converge."""
    rng = np.random.default_rng(8)
    X, _ = _make_synthetic_graph_signals(6, 500, rng)
    with pytest.warns(RuntimeWarning, match="did not converge"):
        learn_graph(X, max_iter=1, verbose=False)


def test_learn_graph_bad_inputs():
    """Test error handling for invalid inputs."""
    rng = np.random.default_rng(9)
    X, _ = _make_synthetic_graph_signals(6, 500, rng)

    with pytest.raises(ValueError, match="alpha must be"):
        learn_graph(X, alpha=0)
    with pytest.raises(ValueError, match="alpha must be"):
        learn_graph(X, alpha=-1)
    with pytest.raises(ValueError, match="beta must be"):
        learn_graph(X, beta=-1)
    with pytest.raises(ValueError, match="must be 2D"):
        learn_graph(np.zeros(6))
    with pytest.raises(ValueError, match="must be 2D"):
        learn_graph(np.zeros((2, 6, 6, 6)))
    with pytest.raises(ValueError, match="n_nodes mismatch"):
        learn_graph([X[:, :100], X[:4, :100]])
    with pytest.raises(ValueError, match="complex-valued"):
        learn_graph(1j * X)
    with pytest.raises(RuntimeError, match="empty"):
        learn_graph(np.zeros((0, 6, 100)))
    with pytest.raises(ValueError, match="at least 2 nodes"):
        learn_graph(X[:1])
