# This file contains additional metadata about MNE-Connectivity, beyond what is contained in `pyproject.toml`.
# This information is used by the actions in MNE-Tools to auto-update minimum dependency versions.
spec_zero_update_packages:
  - matplotlib
  - mne-qt-browser
  - nibabel
  - nilearn
  - numba
  - numpy
  - pandas
  - pyvista
  - pyvistaqt
  - scikit-learn
  - scipy
