blank_issues_enabled: true
contact_links:
  - name: 💬 MNE forum
    url: https://mne.discourse.group/
    about: Use the MNE forum to ask (and answer) concrete technical questions or about the usage of MNE-Connectivity
