name: code-style
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: [main, maint/0.2, maint/0.3, maint/0.4]
  workflow_dispatch:

jobs:
  style:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools
          python -m pip install --progress-bar off .[style]
      - name: Run isort
        uses: isort/isort-action@master
      - name: Run black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
      - name: Run Ruff
        run: ruff check .
      - name: Run codespell
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          check_hidden: true
          skip: './.git,./build,./.mypy_cache,./.pytest_cache,./mne_icalabel/iclabel/network/assets'
          ignore_words_file: ./.codespellignore
      # - name: Run pydocstyle
      #   run: pydocstyle .
      - name: Run toml-sort
        run: toml-sort pyproject.toml --check
      - name: Run yamllint
        run: yamllint . -c .yamllint.yml --strict
