name: PyPi Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install .[build]
          pip install twine wheel

      - name: Build and publish to PyPi
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          python -m twine upload --repository pypi dist/*
